<?php
    $this->headTitle("Delete Item");
?>
<p>Are you sure want delete
    '<?php echo $this->escape($this->item['title']); ?>' 
    '<?php echo $this->escape($this->item['text']); ?>'?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->item['id']; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>