<?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('ZF SKELETON');

    echo $this->doctype();
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
	<head>
		<?php echo $this->headMeta();?>
		<?php echo $this->headTitle();?>
		<link href="<?php echo $this->baseUrl(). '/css/bootstrap.css'; ?>" rel="stylesheet">
		<link href="<?php echo $this->baseUrl(). '/css/bootstrap-responsive.css'; ?>" rel="stylesheet">
		<link href="<?php echo $this->baseUrl(). '/css/style.css'; ?>" rel="stylesheet">
		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link rel="shortcut icon" href="<?php echo $this->baseUrl(). '/img/favicon.ico'; ?>">
		<script src="<?php echo $this->baseUrl(). '/js/jquery.js'; ?>"></script>
		<script src="<?php echo $this->baseUrl(). '/js/bootstrap.js'; ?>"></script>
	</head>
	<body>
		<div class="container">
			<h1>
				<?php echo $this->escape($this->title);	?>
			</h1>
			<?php echo $this->layout()->content; ?>
			<hr />
		
			<footer>
				<p>&copy; Company 2012</p>
			</footer>
		</div>
	</body>
</html>